### ISSUE TITLE
Players are unable to join server

### ISSUE THREAD

**Issue by REALMWTH** [SuCraft/Suki#4]
```
java.lang.NullPointerException: Cannot read field "initial" because "org.sucraft.suki.configuration.SukiGlobalConfiguration.get().networkConstrainedChunkSending.maxChunkPacketsInTransit" is null
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:544) ~[?:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:763) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:192) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:92) ~[?:?]        at net.minecraft.network.Connection.tick(Connection.java:1432) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1439) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[suki-1.19.2.jar:git-Suki-"8335a8d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by MartijnMuijsers** [comment]
Thank you for the issue! It is fixed.

**Comment by REALMWTH** [comment]
@MartijnMuijsers nah, thank YOU for awesome job ;)
